gems:
  - jekyll-coffeescript
  - jekyll-github-metadata

sass:
  sass_dir: _sass

fade: 5s
cycle_ms: 20000
practices_url: https://ashtanga.github.io/practice.json
spacex_url: https://api.spacexdata.com/v1/launches/upcoming
spacex_id_url: https://api.spacexdata.com/v1/launches/
